### ISSUE TITLE
"Install" and "build" buttons on extension builder are greyed out

### ISSUE THREAD

**Issue by jni** [jarryliu/EZProxy#2]
I can't click them so I can't install this.

Thanks for any help!

<img width="812" alt="screen shot 2015-09-02 at 6 01 06 pm" src="https://cloud.githubusercontent.com/assets/492549/9636618/abfd0716-519c-11e5-8418-8d6501bc0804.png">

**Comment by jarryliu** [comment]
I don’t know why you can’t install it. From my mac it only shows “No Safari Extension Certificate”, so I was allowed to install the extension. 

![screen shot 2015-09-02 at 11 24 48 am](https://cloud.githubusercontent.com/assets/6811482/9637237/46bc98da-5165-11e5-8122-9b0920a2b696.jpg)

My only guess is that your apple id has to be a developer , whereas you do not need to pay for the membership.

BTW: current version of the extension only supports WUSTL proxy. I haven’t added all the EZproxy proxies.

**Comment by jni** [comment]
@jarryliu I think you're right that I would need a developer ID to install it. Oh well. =) Re: WUSTL, I thought it would probably be fairly easy to change to UniMelb. =)
